#!/bin/bash

cd /home/elie/Documents/Project/Post-XVP-Data/
for f in */
do 
	echo ${f:0:5} 
	pwd
	mkdir /home/elie/Documents/WebSite/Spectra/Post-XVP/${f:0:5}/
	cp ${f:0:5}/${f:0:5}_sgra_1.25asec.pi /home/elie/Documents/WebSite/Spectra/Post-XVP/${f:0:5}/
	cp ${f:0:5}/${f:0:5}_sgra_1.25asec_bkg.pi /home/elie/Documents/WebSite/Spectra/Post-XVP/${f:0:5}/
	cp ${f:0:5}/${f:0:5}_sgra_1.25asec.rmf /home/elie/Documents/WebSite/Spectra/Post-XVP/${f:0:5}/
	cp ${f:0:5}/${f:0:5}_sgra_1.25asec.corr.arf /home/elie/Documents/WebSite/Spectra/Post-XVP/${f:0:5}/
done


